### ISSUE TITLE
use module.rules instead of module.loaders for webpack2

### ISSUE THREAD

**Issue by marcofugaro** [andywer/webpack-blocks#143] opened 2017-04-19 10:54 UTC
`modules.loaders` was renamed in `modules.rules` in webpack 2, [here are the docs](https://webpack.js.org/configuration/module/#module-rules)

Would be easier when adding custom loaders, to merge the with the default loaders.

Here is the line I'm referring to https://github.com/andywer/webpack-blocks/blob/master/packages/webpack2/index.js#L78

Also the example in the README needs to be updated.

**Comment by andywer** [comment] 2017-04-19 12:08
It's on its way. 1.0 release will be webpack 2 only and use `module.rules` 😉
See #134.

Duplicate of #111

**Comment by andywer** [comment] 2017-04-19 12:08
Sorry for the slow progress on 1.0, though!

**Closed** 2017-04-19 12:08 UTC
Labels: duplicate

**Comment by marcofugaro** [comment] 2017-04-19 12:13
Nice!
