### ISSUE TITLE
Build fails when set exclude option for CSS Modules and/or PostCSS

### ISSUE THREAD

**Issue by langovoi** [andywer/webpack-blocks#133] opened 2017-03-14 21:32 UTC
Hello! Thanks for your awesome project, but it seems I found a bug.

When I use ```cssModules``` with exclude option and import not excluded css, I got next error:
```
ERROR in ./~/css-loader!./~/style-loader!./~/css-loader?importLoaders=1&localIdentName=[name]--[local]--[hash:base64:5]&modules!./components/SocketStatus/index.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../node_modules/css-loader/index.js?importLoaders=1&localIdentName=[name]--[local]--[hash:base64:5]&modules!./index.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!../../node_modules/style-loader/addStyles.js")(content, {});
  8 | if(content.locals) module.exports = content.locals;

 @ ./components/SocketStatus/index.css 4:14-229 13:2-17:4 14:20-235
 @ ./components/SocketStatus/index.jsx
 @ ./pages/App/index.jsx
 @ ./pages/Home/index.jsx
 @ ./App/index.jsx
 @ ./index.js
 @ multi (webpack)-dev-server/client?https://0.0.0.0:8080 webpack/hot/dev-server react-hot-loader/patch ./index.js webpack/hot/only-dev-server
```

Removing of ```postcss``` not helped, also if remove ```cssModule``` and add exclude option for ```postcss``` got similar error.

I think it happens because after adding new rule with exclude option (```cssModules``` or ```postcss```), default rule for styles still process excluded files. Maybe add include for default rule with exclude from ```cssModules``` and/or ```postcss```?

My config:
```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const {createConfig, entryPoint, setOutput, sourceMaps, addPlugins} = require('@webpack-blocks/webpack2');
const babel = require('@webpack-blocks/babel6');
const devServer = require('@webpack-blocks/dev-server2');
const postcss = require('@webpack-blocks/postcss');
const cssModules = require('@webpack-blocks/css-modules');

module.exports = createConfig([
    entryPoint([
        'react-hot-loader/patch',
        './index.js'
    ]),
    setOutput('./[name].js'),
    addPlugins([
        new HtmlWebpackPlugin({
            inject: true,
            template: './index.html'
        }),
        new webpack.NamedModulesPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
    ]),
    babel(),
    postcss(),
    cssModules({
        exclude: /\/node_modules\//
    }),
    devServer(),
    sourceMaps('eval')
]);
```

**Comment by andywer** [comment] 2017-03-14 22:18
Hey @langovoi and thanks.

Yeah, that is most probably the case. 👍 for the good description and details.

You can try to use `createConfig.vanilla()` instead of `createConfig()` for now, so the default CSS loader will not be added. I hope that is enough to fix it for now, since we plan to drop those implicit default loaders in version 1.0/2.0 anyway.

Tell me if that works for you.

**Comment by langovoi** [comment] 2017-03-14 22:47
@andywer yeah, it's work.

Final config (for help another people), with ```postcss``` for default rule and ```cssModules``` with ```postcss``` with excluding for ```node_modules```.

```js
...
const {createConfig, entryPoint, setOutput, sourceMaps, addPlugins} = require('@webpack-blocks/webpack2');
const postcss = require('@webpack-blocks/postcss');
const cssModules = require('@webpack-blocks/css-modules');

module.exports = createConfig.vanilla([
    (context) => ({
        module: {
            loaders: [
                {
                    test: context.fileType('text/css'),
                    loaders: ['style-loader', 'css-loader'],
                    include: /\/node_modules\//
                }, {
                    test: context.fileType('image'),
                    loaders: ['file-loader']
                }, {
                    test: context.fileType('application/font'),
                    loaders: ['file-loader']
                }, {
                    test: context.fileType('audio'),
                    loaders: ['url-loader']
                }, {
                    test: context.fileType('video'),
                    loaders: ['url-loader']
                }
            ]
        },
        plugins: [],
        resolve: {
            extensions: ['.js', '.jsx', '.json']
        }
    }),
    ...
    postcss(),
    postcss(undefined, {
        exclude: /\/node_modules\//
    }),
    cssModules({
        exclude: /\/node_modules\//
    }),
]);
```

**Comment by langovoi** [comment] 2017-03-14 22:51
@andywer maybe you update README for ```postcss``` and ```cssModules```?

Also ```postcss``` don't have info about ```exclude``` and ```cssModules``` have info that ```node_modules``` default excluded, but it's wrong.

**Comment by andywer** [comment] 2017-03-15 08:56
Good that it works, but sorry for the inconvenience! That doesn't look very elegant anymore... Maybe you want to watch the repo and upgrade to the next major version as soon as its 1st beta is out?

> Also postcss don't have info about exclude and cssModules have info that node_modules default excluded, but it's wrong.

Not sure what you mean (this quoted sentence). But that is definitely on the schedule for the upcoming next major version. This ugly `node_modules` inclusion issue needs to be fixed.

**Comment by langovoi** [comment] 2017-03-15 09:08
> Maybe you want to watch the repo and upgrade to the next major version as soon as its 1st beta is out?

No problem, I will be wait first beta 👌🏻

> Not sure what you mean

```@webpack-blocks/postcss``` don't have information in README about ```exclude``` option. (but it present in code: https://github.com/andywer/webpack-blocks/blob/master/packages/postcss/index.js#L12)

```@webpack-blocks/css-modules``` have information about ```exclude``` option in README, but have next notice:
> Defaults to /\/node_modules\// regex.

it's incorrect.

**Comment by andywer** [comment] 2017-03-15 09:19
Ahhhh. True :)

Will need to fix that! Must be an unfortunate left-over, since we changed the default exclusion behavior before.

**Comment by andywer** [comment] 2017-08-16 18:52
I think this has already been fixed by improving the documentation and the new `match()` (set `exclude` there).

Closing the issue. Feel free to re-open if you think the issue is not fixed yet.

**Closed by andywer** 2017-08-16 18:52 UTC
Labels: improve documentation, question
